### ISSUE TITLE
Error within wildduck

### ISSUE THREAD

**Issue by Lee182** [louis-lau/wildduck-dockerized#12]
_1          | /wildduck/api.js:164
wildduck_1          |     origins: [].concat(config.api.cors.origins || ['*']),
wildduck_1          |                                        ^
wildduck_1          | 
wildduck_1          | TypeError: Cannot read property 'origins' of undefined
wildduck_1          |     at Object.<anonymous> (/wildduck/api.js:164:40)
wildduck_1          |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
wildduck_1          |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
wildduck_1          |     at Module.load (internal/modules/cjs/loader.js:950:32)
wildduck_1          |     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
wildduck_1          |     at Module.require (internal/modules/cjs/loader.js:974:19)
wildduck_1          |     at require (internal/modules/cjs/helpers.js:92:18)
wildduck_1          |     at Object.<anonymous> (/wildduck/worker.js:8:13)
wildduck_1          |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
wildduck_1          |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

**Comment by korowiov** [comment]
https://github.com/nodemailer/wildduck/issues/331

**Comment by louis-lau** [comment]
⬆️ I'll move that issue back to this repo since it seems this is intended behaviour for wildduck. This should be fixed with the latest setup image. If you want to use your existing config you can apply these changes to it: https://github.com/nodemailer/wildduck-dockerized/commit/b685ea10fd3c57941b3297545ca56074b80e205f
