### ISSUE TITLE
How to use other https reverse proxy properly?

### ISSUE THREAD

**Issue by dumprop** [louis-lau/wildduck-dockerized#15]
Currently I try to install wildduck dockerized on caprover, which has https certificate
I changed port "443" to "1443" (as example) gets "404 page not found" text
Same text I gets on 180 (ex 80) port, but there something "Found" (no any useful page)
On 443/80 all are ok

**Comment by louis-lau** [comment]
I'd first remove traefik from your docker compose file.

**Comment by dumprop** [comment]
> 
> 
> I'd first remove traefik from your docker compose file.

Is impossible to use traefik for smtp/imap only?

**Comment by louis-lau** [comment]
Without port 80 or port 443 pointing to traefik, it can't get the correct certificates automatically. I may be possible, but not that practical.

**Comment by louis-lau** [comment]
You can bindmount certificates into the containers, and edit the configs to have the services use them instead of using Traefik. This doesn't sound like an issue with wildduck-dockerized to me though, so I'm closing it for now.

**Comment by dumprop** [comment]
> 
> 
> Without port 80 or port 443 pointing to traefik, it can't get the correct certificates automatically. I may be possible, but not that practical.

Yes, but probably switching from http to dns challenge?

**Comment by louis-lau** [comment]
I didn't even think of that! Sure, that's an option. Traefik supports this quite well I believe.
