### ISSUE TITLE
Can't create a new account

### ISSUE THREAD

**Issue by jet10000** [louis-lau/wildduck-dockerized#2]
After I installed it according to the document, I opened mail.mydomain.com, but I could not create an account.

**Comment by louis-lau** [comment]
Why not?

**Comment by louis-lau** [comment]
What I mean by that, is that I really need more details. Logs, screenshots, anything.

**Comment by louis-lau** [comment]
Hey @jet10000, you seem to have a habit of opening issues, but never following up. Open source contributers are giving you their time (for free), I think it would only be fair if you'd do the same. 😁 

Closing this due to lack of response. I can reopen it if you'd like to bother responding.
