### ISSUE TITLE
Example of List-Unsubscribe header on config (or support)

### ISSUE THREAD

**Issue by ccovarrubias** [louis-lau/wildduck-dockerized#21]
Hello,

My use case: All my email is marked as SPAM by google (on the recent days, it is marked as REJECTED and is not delivered), I have implemented almost all the recommended practices by google (see https://support.google.com/mail/answer/81126?sjid=17926696693480439006-NA)

I have also read that the List-Unsubscribe header is well known as a good practice for google. After taking a look on the nodemailer/wildduck code, I see that it is supported (if the header is passed https://github.com/nodemailer/wildduck/blob/1a800fd7be54392478e399257e7b0f0dd2db3820/lib/api/messages.js#L869-L870),  but is not clear to me if you pass the header somewhere, or if I can configure it on the .toml files.

I appreciate your help.

Carlos

**Comment by ccovarrubias** [comment]
a couple mail-health reports:

https://mxtoolbox.com/emailhealth/mail.petzer.com.mx/
https://grademyemail.co/mx-record-lookup?domain=petzer.com.mx

and my score with mail-tester:
https://www.mail-tester.com/test-rn583injr&reloaded=1

I have the DKIM, DMARC, SPF, reverse DNS and they seem to be ok, but even so, Google marks the emails as REJECTED

**Comment by louis-lau** [comment]
A global list-unsubscribe header for wildduck doesn't make much sense. The header is used to unsubscribe from mailing lists and newsletters. Your mailing list or newsletter software should set them, as the header content is completely dependent on the specific mailing list or newsletter.

Google also looks at domain reputation and content. That's more likely to be the issue than a missing list unsubscribe.

**Comment by louis-lau** [comment]
Your spf record also lists google ips. Is it possible the domain is registered with Google Workspace? Could be a factor.

**Comment by ccovarrubias** [comment]
> A global list-unsubscribe header for wildduck doesn't make much sense. The header is used to unsubscribe from mailing lists and newsletters. Your mailing list or newsletter software should set them, as the header content is completely dependent on the specific mailing list or newsletter.
> 
> Google also looks at domain reputation and content. That's more likely to be the issue than a missing list unsubscribe.

You have a good point. I'll check if I can setup the unsuscribe header from the intermediate provider (in fact, it is a pure nodemailer microservice that uses as smtp provider my self-hosted wildduck).
