### ISSUE TITLE
Haraka doesn't accept tls certificates

### ISSUE THREAD

**Issue by githubapache2** [louis-lau/wildduck-dockerized#24]
Setup:
edited tls.ini with cert and ley value for letsencrypt certificate as privkey.pem and fullchain.pem

Following error code:
Starting up Haraka version 2.8.27
[INFO] [-] [core] Loading plugins
[INFO] [-] [core] Loading plugin: spf
[INFO] [-] [core] Loading plugin: dkim_verify
[INFO] [-] [core] Loading plugin: rspamd
[INFO] [-] [core] Loading plugin: tls
[INFO] [-] [core] loading tls.ini
[INFO] [-] [core] Generating a 2048 bit dhparams file at /app/config/dhparams.pem
[INFO] [-] [core] Loading plugin: wildduck
[CRIT] [-] [core] Error: spawn openssl ENOENT
[CRIT] [-] [core]     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
[CRIT] [-] [core]     at onErrorNT (internal/child_process.js:465:16)
[CRIT] [-] [core]     at processTicksAndRejections (internal/process/task_queues.js:80:21)
[NOTICE] [-] [core] Shutting down

**Comment by louis-lau** [comment]
> Error: spawn openssl ENOENT

This may be very obvious, but it's worth a try: Is openssl installed?

**Comment by louis-lau** [comment]
Sorry. Just noticed this is an issue on wildduck-dockerized. To answer my own question: no.

**Comment by louis-lau** [comment]
I'm planning on redoing a big part of this repo and automate all docker builds to happen with wildduck releases. This will be fixed when I do that, in the meantime you should be able to create your own dockerfile where openssl is installed.

**Comment by githubapache2** [comment]
That are great news! I spent a lot of hours to get my setup with wildduck-dockerized to run webmail, api, portainer, graylog all on the same https port without a subdomain and it works great. I could post my traefik setup/docker-compose for it if interrested. 

EDIT: Added openssl to Dockerfile and built new docker image. Now Haraka works fine with certs.
