### ISSUE TITLE
Why Traefik? 

### ISSUE THREAD

**Issue by dumprop** [louis-lau/wildduck-dockerized#4]
https://dev.to/mark_saward/caddy-vs-traefik-1dkp
https://github.com/wemake-services/wemake-django-template/issues/36

Caddy can renew certs too

**Comment by andris9** [comment]
WildDuck example use mainly nginx but it does not matter which proxy/load balncer to use. For ports 25, 110, 587 etc, that use STARTTLS you need to provide valid certificates directly to WildDuck as TLS termination is handled by WildDuck and can’t be easily passed to a proxy service.

**Comment by louis-lau** [comment]
1. Because it needs to proxy TCP services. Caddy only has experimental support for this by building it with https://github.com/mholt/caddy-l4, which can only use JSON configuration at this time.
1. Why not?

If you feel different feel free to use caddy in your setup. This repo provides the docker containers, *example* configuration, and an *example* docker-compose that works out of the box. There is nothing tying you to Traefik.

**Comment by dumprop** [comment]
> WildDuck example use mainly nginx but it does not matter which proxy/load balncer to use. For ports 25, 110, 587 etc, that use STARTTLS you need to provide valid certificates directly to WildDuck as TLS termination is handled by WildDuck and can’t be easily passed to a proxy service.

But why not caddy, which written in Go, and it has embedded acme?
Also, [readme](https://github.com/nodemailer/wildduck-dockerized/blob/master/README.md) says that "No STARTTLS support, only SSL/TLS"


>     1. Because it needs to proxy TCP services. Caddy only has experimental support for this by building it with https://github.com/mholt/caddy-l4, which can only use JSON configuration at this time.
> 
>     2. Why not?
> 
> 
> If you feel different feel free to use caddy in your setup. This repo provides the docker containers, _example_ configuration, and an _example_ docker-compose that works out of the box. There is nothing tying you to Traefik.

Yes, but I'd like to have an example configuration for my preferred web server

**Comment by andris9** [comment]
You can use Caddy (or any other proxy) but you have to generate certificates for WildDuck STARTTLS separately or somehow export from Caddy.

**Comment by louis-lau** [comment]
> But why not caddy

Like I said above, it doesn't (stably) support proxying tcp services right now.

> it has embedded acme

Traefik has embedded ACME, that's the entire point. 

> No STARTTLS support, only SSL/TLS

Correct. Caddy wouldn't provide this either. The only way to provide this is to write the certificates to disk, and have haraka, wildduck, and zometa use the certificates directly. And also have something reload/restart those services when the certificate changes.

I would prefer to keep the example docker-compose simple to maintain and understand, so I've opted to have the example not support STARTTLS, but only TLS. This way only the proxy (here Traefik) is responsible for TLS certificates. TCP proxies can not handle STARTTLS.

> but I'd like to have an example configuration for my preferred web server

If you're willing to send a pull request for a complete docker-compose example which uses caddy, i'd be willing to accept it as an alternate example.

**Comment by andris9** [comment]
Btw when I said that you can use any proxy then I meant that you can use any HTTP proxy in front of the webmail or API servers. To proxy IMAP/TCP/POP3 you need an actual TCP proxy as @louis-lau also stated or serve them directly.
