### ISSUE TITLE
Custom SSL Certificates

### ISSUE THREAD

**Issue by AviiNL** [louis-lau/wildduck-dockerized#5]
Hello,

I can't find anything about using my own custom SSL certificates for wildduck.

I have certificates on my host machine, any way I can use them inside the containers for wildduck TLS/SSL etc?

Thank in advance,
Avii.

**Comment by louis-lau** [comment]
Heya,

For wildduck you can set them here:
https://github.com/nodemailer/wildduck/blob/master/config/tls.toml

Haraka and zonemta have similar config lines.

However, wildduck-dockerized uses traefik to automatically fetch certificates for you from let's encrypt. There's no need to manually mess with certificates.

**Comment by AviiNL** [comment]
If I specify a path on my host system in `tls.toml`, it won't be available inside the container, how am I supposed to map this?

Also due to the fact that I'm behind a bunch of proxies, I am unable to use automated letsencrypt stuff inside my vms.
My proxy server creates certificates and shares them via a shared vmdk to all the other vms that require certs.

**Comment by louis-lau** [comment]
That's more of a docker question! Specify bindmounts in your docker-compose file to make files from your host system available inside containers:
https://docs.docker.com/storage/bind-mounts/
https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes

> I am unable to use automated letsencrypt stuff inside my vms.

Fair enough. In that case you can remove Traefik and all the traefik labels from your docker-compose and expose the ports directly. These are the ports Traefik exposes:
```
      - 80:80/tcp   <- redirect to https
      - 443:443/tcp <- wildduck-webmail (port 80 on the wildduck-webmail container itself)
      - 993:993/tcp <- wildduck IMAPS
      - 995:995/tcp <- wildduck POP3S
      - 465:465/tcp <- zonemta SMTPS
```

Docker experience would be good for a custom setup. Given you currently don't know how to expose files from the host system inside your containers, I'd recommend first learning more about docker 😁

**Comment by louis-lau** [comment]
Oh, and in the default config TLS is disabled in all applications, because Traefik handles it. Aside from specifying the certificates you'll also have to enable it. For example in wildduck for imap:
https://github.com/nodemailer/wildduck-dockerized/blob/master/default-config/wildduck/imap.toml#L3-L8

**Comment by AviiNL** [comment]
Looking at Traefik, that is an amazing piece of software, it looks like I can specify custom certs via that, I'll try that route so I can still leverage the awesomeness of Traefik :)
