### ISSUE TITLE
strange happened

### ISSUE THREAD

**Issue by yarosdev** [louis-lau/wildduck-dockerized#7]
mongo db has been dropped suddenly 

![image](https://user-images.githubusercontent.com/6161950/110819585-fdd17500-8296-11eb-9c03-d54fd731941b.png)

**Comment by louis-lau** [comment]
Seems someone dropped your data, and wants you to pay to recover it. Did you open up your database to the internet?

**Comment by yarosdev** [comment]
oh yes I have opened port to the world...

**Comment by louis-lau** [comment]
I hope you were still only testing and there wasn't anything important in there 🙃 

Mongodb isn't secure by default. If you want to open it up to the world make sure you configure authentication for it. I would just never open it to the internet though, safer that way.
