### ISSUE TITLE
dkim not working

### ISSUE THREAD

**Issue by yarosdev** [louis-lau/wildduck-dockerized#8]
it does not sign emails at all

**Comment by yarosdev** [comment]
Any idea why it doesnt work for image:nodemailer/zonemta-wildduck ?
I have installed on bare server https://github.com/nodemailer/wildduck/tree/master/setup and dkim works well, I have created docker image on rancher and passed config from working bare setup version.

**Comment by yarosdev** [comment]
Is it possible to get help from you using $$$?

**Comment by louis-lau** [comment]
> Any idea why it doesnt work for image:nodemailer/zonemta-wildduck

I'll have to test and check. There's shouldn't be any difference between the normal install and the install in the docker container. I'd have to find some free time in a weekend to check.

> Is it possible to get help from you using $$$?

I assume you mean me :)? I'm available for a little freelance work in the weekends. I'd charge about €120 an hour. You can contact me for that on louis@laureys.me if you desire.

**Comment by yarosdev** [comment]
> I'd have to find some free time in a weekend to check.

It would be great!

> I'd charge about €120 an hour.

It is too much for me:)

**Comment by yarosdev** [comment]
how is it going?

**Comment by yarosdev** [comment]
Any news about this ?

**Comment by AaronPorts** [comment]
The main reason is that there is no configured dkim plugin in zone-mta. I think it will be better to put this procedure inside setup.sh. For now you can do as follows: replace all files from ./config/zone-mta/ to ./config/zone-mta/config folder and create following ./config/zone-mta/config/plugins/dkim.toml file:
```
["dkim"]
enabled = true 
```
Find an example of the plugin [here](https://github.com/zone-eu/zone-mta-template/blob/master/plugins/example-dkim.js), copy it inside ./config/zone-mta/plugins/dkim.js, generate openssl certificates and place them inside ./config/zone-mta/keys ([here](https://github.com/nodemailer/wildduck/blob/master/setup/09_install_zone_mta.sh) you can find generation procedure of certs, DKIM_DNS and DKIM_SELECTOR ). Replace DKIM_DOMAIN_NAME, DKIM_SELECTOR and DKIM_KEY in ./config/zone-mta/plugins/dkim.js. Don't forget to add next TXT record for DNS verification DKIM_SELECTOR._domainkey.MAILDOMAIN with DKIM_DNS value and mount volumes in docker zonemta:
```
    volumes:
      - ./config/zone-mta/config:/app/config
      - ./config/zone-mta/keys:/app/keys
      - ./config/zone-mta/plugins:/app/plugins
```

**Comment by louis-lau** [comment]
@AaronPorts Het wildduck zonemta plugin does the dkim signing with keys from the database. There is no need for a separate dkim plugin.

I still haven't been able to find the time to look into this, sorry

**Comment by AaronPorts** [comment]
@louis-lau Do you mean using http://localhost:8080/dkim api call? I tried it but no luck.

**Comment by louis-lau** [comment]
Yep, if you add keys there with the right selector the wildduck zonemta plugin _should_ take care of it.

**Comment by MinisculeGirraffe** [comment]
Can confirm. DKIM key is added with the proper selector and the containerized setup doesn't sign DKIM headers.  Specific to the dockerized version.  DKIM keys have been added via the API.

Will edit later with logs.

**Comment by louis-lau** [comment]
It looks like I made a mistake in the default zone-mta configuration. A lot of thanks to @taxilian for figuring this out.

This should fix it: https://github.com/nodemailer/wildduck-dockerized/commit/b1ba2c61a9fb1d99135aec9911e3b73041d5e5ce

Either run the setup from scratch, or make the same change to your current config, and let me know if dkim now works for you!

**Comment by fluidum** [comment]
As instructions were not clear for me (commit dedc7cacc3e1e942c1f73fe037115eca37d206ee) I share how I did it, based on https://github.com/nodemailer/wildduck/blob/master/setup/09_install_zone_mta.sh

1. I entered into zonemta container like so 
`podman exec -it wildduck-zonemta sh`

```
export MAILDOMAIN=example.com
export DKIM_SELECTOR=feb2025

cd /app/keys
# Many registrar limits dns TXT fields to 255 char. 1024bit is almost too long:-\
openssl genrsa -out "$MAILDOMAIN-dkim.pem" 1024
chmod 400 "$MAILDOMAIN-dkim.pem"
openssl rsa -in "$MAILDOMAIN-dkim.pem" -out "$MAILDOMAIN-dkim.cert" -pubout
DKIM_DNS="v=DKIM1;k=rsa;p=$(grep -v -e '^-' $MAILDOMAIN-dkim.cert | tr -d "\n")"

DKIM_JSON=`DOMAIN="$MAILDOMAIN" SELECTOR="$DKIM_SELECTOR" node -e 'console.log(JSON.stringify({
  domain: process.env.DOMAIN,
  selector: process.env.SELECTOR,
  description: "Default DKIM key for "+process.env.DOMAIN,
  privateKey: fs.readFileSync("/app/keys/"+process.env.DOMAIN+"-dkim.pem", "UTF-8")
}))'`

echo $DKIM_DNS
echo $DKIM_JSON
exit
```

2. Next I created TXT record into my nameserver using $DKIM_SELECTOR and $DKIM_DNS

3. I entered into wildduck container like so 
`podman exec -it wildduck sh`
>Source: https://docs.wildduck.email/docs/wildduck-api/update-dkim-key/

```
curl -L 'localhost:8080/dkim' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-d '<put here your $DKIM_JSON>'
```

4. done - test your outgoing emails

**Comment by louis-lau** [comment]
@fluidum You can just post to the api and wildduck will generate it for you. No real need to go through the trouble of egenrating it yourself. You should use a 2048 bit key nowadays. If your dns host doesn't support automatic splitting of TXT records longer than 255, you can do it yourself and submit them as split 255 long parts.

https://docs.wildduck.email/docs/wildduck-api/update-dkim-key
https://www.mailhardener.com/tools/dns-record-splitter

**Comment by fluidum** [comment]
Thanks @louis-lau 
To be honest, I did it so yesterday - POST with domain and selector against dkim endpoint. I received a TXT record and Cloudflare split the TXT record after saving it (probably because of char limits), but still Gmail said it was signed by invalid public key.

Will try again to see if the dns record splitter helps.

**Comment by louis-lau** [comment]
Cloudflare does support auto splitting, it shouldn't cause any issues at all as long as you copy paste it correctly.
